# Generated by Django 3.0.8 on 2020-07-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('engine_type', models.CharField(max_length=255)),
                ('transmission', models.CharField(max_length=255)),
                ('horse_power', models.IntegerField(max_length=20)),
                ('cylinders', models.IntegerField(max_length=20)),
            ],
        ),
    ]
