# Generated by Django 3.0.8 on 2020-07-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_ke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cylinders',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='horse_power',
            field=models.IntegerField(),
        ),
    ]
