# Generated by Django 3.0.8 on 2020-07-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_ke', '0003_car_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(default='', upload_to='vehicles/'),
        ),
    ]
